- description: check OCP for insecure routes
  executionEnabled: true
  group: openshift
  id: f7ef4a51-6417-4b97-a658-f85527185447
  loglevel: INFO
  name: check insecure OC routes
  nodeFilterEditable: false
  notification:
    onfailure:
      email:
        attachLog: true
        recipients: administrator@opendevstack.org
        subject: OpenDevsStack OCP security alert!
  options:
  - description: the openshift token to access OpenDevsStack OCP
    name: openshift_api_token
    required: true
    secure: true
    storagePath: keys/openshift-api-token
    valueExposed: true
  - description: _ separated project names
    name: project_names
  schedule:
    month: '*'
    time:
      hour: '21'
      minute: '51'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: create job dir
      exec: mkdir /tmp/rundeck_${job.id}_${job.execid}
    - description: clone repo and execute script
      exec: cd /tmp/rundeck_${job.id}_${job.execid} && git clone ${globals.bitbucket_sshhost}/opendevstack/ocp-templates.git && cd ocp-templates && git checkout -b production origin/production
    - description: build container
      exec: cd /tmp/rundeck_${job.id}_${job.execid}/ocp-templates && sudo docker build -t oc .
    - exec: cd /tmp/rundeck_${job.id}_${job.execid}/ocp-templates && sudo docker run --rm oc /bin/bash -c "ls -ls && ./check_ocp_secure_routes.sh -h ${globals.openshift_apihost} -t ${option.openshift_api_token} -p ${option_project_names}"
    keepgoing: false
    pluginConfig:
      WorkflowStrategy:
        node-first: null
    strategy: node-first
  uuid: f7ef4a51-6417-4b97-a658-f85527185447

